/* Single-file local backup: cases, notes, document metadata and uploaded bytes. */
const backupLimit=100*1024*1024;
let backupBusy=false,backupCandidate=null;
const backupNav=document.createElement('button');backupNav.className='nav-item';backupNav.dataset.view='backup';backupNav.textContent='Backup';document.querySelector('#nav').append(backupNav);
const backupSection=document.createElement('section');backupSection.id='backup';backupSection.className='view';backupSection.innerHTML=`<div class="panel"><h3>Backup e ripristino</h3><p>Salva pratiche, note, fascicoli e allegati caricati in un unico file. Conserva una copia sul computer o su un archivio sicuro.</p><div class="backup-actions"><button class="primary" id="exportBackup">Esporta backup completo</button><label class="backup-label">Seleziona un backup da ripristinare<input id="backupFile" type="file" accept=".json,.pfbackup.json"></label></div><p class="meta">Sono inclusi tutti i dati delle pratiche, anche quelle importate da Excel. Scadenze, bozze e storico degli invii manuali sono inclusi. Email dimostrative, periti e compensi dimostrativi non sono dati operativi salvati. Il backup è in chiaro: chi possiede il file può leggerne il contenuto.</p><p id="backupMessage" role="status" aria-live="polite"></p><div id="backupPreview"></div><button class="danger-btn" id="restoreBackup" disabled>Ripristina e sostituisci i dati</button></div>`;
document.querySelector('.main').append(backupSection);
backupNav.onclick=()=>{document.querySelectorAll('.nav-item,.view').forEach(el=>el.classList.remove('active'));backupNav.classList.add('active');backupSection.classList.add('active');document.querySelector('#pageTitle').textContent='Backup';document.querySelector('#pageSubtitle').textContent='Esportazione e recupero dei dati locali';};
const backupStatus=msg=>document.querySelector('#backupMessage').textContent=msg;
function lockBackup(busy){backupBusy=busy;document.querySelector('#exportBackup').disabled=busy;document.querySelector('#backupFile').disabled=busy;document.querySelector('#restoreBackup').disabled=busy||!backupCandidate;document.querySelector('.sidebar').inert=busy;document.querySelector('.topbar').inert=busy;document.querySelectorAll('.view:not(#backup)').forEach(el=>el.inert=busy);}
function toBase64(bytes){let result='';for(let i=0;i<bytes.length;i+=32768)result+=String.fromCharCode(...bytes.subarray(i,i+32768));return btoa(result);}
function fromBase64(text){if(typeof text!=='string'||text.length%4!==0||!/^(?:[A-Za-z0-9+/]{4})*(?:[A-Za-z0-9+/]{2}==|[A-Za-z0-9+/]{3}=)?$/.test(text))throw Error('Allegato codificato in modo non valido.');const raw=atob(text);return Uint8Array.from(raw,c=>c.charCodeAt(0));}
async function fileDigest(bytes){return [...new Uint8Array(await crypto.subtle.digest('SHA-256',bytes))].map(x=>x.toString(16).padStart(2,'0')).join('');}
async function snapshotFiles(keys){if(!keys.length)return new Map();const db=await dbPromise;return new Promise((resolve,reject)=>{const values=new Map(),tx=db.transaction('files','readonly'),s=tx.objectStore('files');for(const key of keys){const r=s.get(key);r.onsuccess=()=>values.set(key,r.result);}tx.oncomplete=()=>resolve(values);tx.onerror=()=>reject(tx.error);tx.onabort=()=>reject(tx.error);});}
async function buildFullBackup(){
 const practiceSnapshot=JSON.parse(JSON.stringify(cases)),docSnapshot=JSON.parse(JSON.stringify(documents));const keys=[...new Set(docSnapshot.map(d=>d.blobKey).filter(Boolean))];const stored=await snapshotFiles(keys);const files=[];let total=0;
 for(const key of keys){const blob=stored.get(key);if(!blob)throw Error('Un allegato non è disponibile: '+docSnapshot.find(d=>d.blobKey===key).name+'. Il backup non è stato esportato.');total+=blob.size;if(total>backupLimit)throw Error('Gli allegati superano il limite di 100 MB per backup.');const bytes=new Uint8Array(await blob.arrayBuffer());files.push({key,mime:blob.type||'application/octet-stream',size:bytes.length,sha256:await fileDigest(bytes),base64:toBase64(bytes)});}
 return {format:'PeriziaFlowBackup',version:3,appVersion:'1.9.1',createdAt:new Date().toISOString(),cases:practiceSnapshot,documents:docSnapshot,files};
}
function backupText(value,label,max=10000){if(typeof value!=='string'||value.length>max)throw Error(label+': testo non valido.');return value;}
function backupId(value,label){backupText(value,label,100);if(!/^[A-Za-z0-9_-]+$/.test(value))throw Error(label+': identificativo non valido.');return value;}
function cleanBackupCase(raw){if(!raw||typeof raw!=='object'||Array.isArray(raw))throw Error('Pratica non valida.');const c={};
 for(const key of ['id','claim','company','insured','type','expert','status','created','category','openedAt','closedAt','liquidationStatus','liquidatedAt']){if(raw[key]!=null)c[key]=backupText(raw[key],key,1000);}
 backupId(c.id,'ID pratica');for(const key of ['claim','company','insured'])if(!c[key]?.trim())throw Error('Pratica senza '+key+'.');
 for(const key of ['amount','requestedAmount','assessedAmount','liquidatedAmount','days'])if(raw[key]!==undefined){if(raw[key]!==null&&(typeof raw[key]!=='number'||!Number.isFinite(raw[key])||raw[key]<0))throw Error('Importo o giorni non validi.');c[key]=raw[key];}
 c.notes=[];if(raw.notes!==undefined){if(!Array.isArray(raw.notes)||raw.notes.length>10000)throw Error('Note non valide.');c.notes=raw.notes.map(n=>({text:backupText(n.text,'Nota',50000),date:backupText(n.date,'Data nota',100)}));}
 c.deadlines=[];if(raw.deadlines!==undefined){if(!Array.isArray(raw.deadlines)||raw.deadlines.length>10000)throw Error('Scadenze non valide.');c.deadlines=raw.deadlines.map(cleanDeadline);const ids=new Set();for(const d of c.deadlines){if(ids.has(d.id))throw Error('ID scadenza duplicato.');ids.add(d.id);}}
 c.reminders=[];if(raw.reminders!==undefined){if(!Array.isArray(raw.reminders)||raw.reminders.length>10000)throw Error('Solleciti non validi.');c.reminders=raw.reminders.map(cleanReminder);const ids=new Set();for(const r of c.reminders){if(ids.has(r.id))throw Error('ID sollecito duplicato.');ids.add(r.id);}}return c;
}
async function validateFullBackup(raw){
 if(!raw||raw.format!=='PeriziaFlowBackup'||![1,2,3].includes(raw.version))throw Error('Il file non è un backup PeriziaFlow compatibile.');
 if(!Array.isArray(raw.cases)||!Array.isArray(raw.documents)||!Array.isArray(raw.files)||raw.cases.length>50000||raw.documents.length>100000||raw.files.length>100000)throw Error('Struttura o quantità dei dati non valida.');
 const restoredCases=raw.cases.map(cleanBackupCase),ids=new Set();for(const c of restoredCases){if(ids.has(c.id))throw Error('ID pratica duplicato.');ids.add(c.id);}
 const docIds=new Set(),fileKeys=new Set();const restoredDocs=raw.documents.map(d=>{if(!d||typeof d!=='object')throw Error('Documento non valido.');const cleaned={id:backupId(d.id,'ID documento'),caseId:backupId(d.caseId,'ID pratica documento'),name:backupText(d.name,'Nome documento',1000),type:backupText(d.type||'Documento','Tipo documento',1000),date:backupText(d.date,'Data documento',100),folder:backupText(d.folder,'Sottocartella',100)};
  if(!ids.has(cleaned.caseId))throw Error('Documento collegato a una pratica assente.');if(!folders.includes(cleaned.folder))throw Error('Sottocartella non riconosciuta.');if(docIds.has(cleaned.id))throw Error('ID documento duplicato.');docIds.add(cleaned.id);
  if(d.blobKey){cleaned.blobKey=backupId(d.blobKey,'ID allegato');fileKeys.add(cleaned.blobKey);}if(d.size!=null){if(!Number.isInteger(d.size)||d.size<0)throw Error('Dimensione documento non valida.');cleaned.size=d.size;}return cleaned;});
 const restoredFiles=[];let total=0;const seen=new Set();
 for(const f of raw.files){const key=backupId(f.key,'ID allegato');if(seen.has(key)||!fileKeys.has(key))throw Error('Allegato duplicato o senza documento.');seen.add(key);
  if(!Number.isInteger(f.size)||f.size<0||f.size>backupLimit)throw Error('Dimensione allegato non valida.');total+=f.size;if(total>backupLimit)throw Error('Limite allegati: 100 MB.');if(typeof f.base64!=='string'||f.base64.length>Math.ceil(f.size/3)*4)throw Error('Dimensione dati allegato non valida.');const bytes=fromBase64(f.base64);if(bytes.length!==f.size||await fileDigest(bytes)!==f.sha256)throw Error('Allegato danneggiato o modificato: '+restoredDocs.find(d=>d.blobKey===key).name);
  restoredFiles.push({key,blob:new Blob([bytes],{type:backupText(f.mime||'application/octet-stream','Tipo file',200)})});
 }
 if(seen.size!==fileKeys.size)throw Error('Il backup non contiene tutti gli allegati richiesti.');for(const d of restoredDocs)if(d.blobKey&&d.size!=null&&d.size!==restoredFiles.find(f=>f.key===d.blobKey).blob.size)throw Error('Dimensione del documento incoerente.');
 return {cases:restoredCases,documents:restoredDocs,files:restoredFiles,createdAt:backupText(raw.createdAt,'Data backup',100),bytes:total};
}
async function applyFullBackup(candidate){
 // Capture metadata before a single atomic IndexedDB replacement; rollback on failure.
 const oldCases=localStorage.getItem('pf_cases'),oldDocs=localStorage.getItem('pf_documents_v5'),oldDemo=localStorage.getItem('pf_v5_demo');
 const caseJSON=JSON.stringify(candidate.cases),docJSON=JSON.stringify(candidate.documents);
 const restoreMeta=()=>{for(const [key,val] of [['pf_cases',oldCases],['pf_documents_v5',oldDocs],['pf_v5_demo',oldDemo]]){if(val===null)localStorage.removeItem(key);else localStorage.setItem(key,val);}};
 try{localStorage.setItem('pf_cases',caseJSON);localStorage.setItem('pf_documents_v5',docJSON);localStorage.setItem('pf_v5_demo','1');}catch(e){restoreMeta();throw e;}
 try{const db=await dbPromise;await new Promise((resolve,reject)=>{const tx=db.transaction('files','readwrite'),store=tx.objectStore('files');store.clear();for(const f of candidate.files)store.put(f.blob,f.key);tx.oncomplete=resolve;tx.onerror=()=>reject(tx.error);tx.onabort=()=>reject(tx.error);});}catch(e){restoreMeta();throw e;}
 cases.splice(0,cases.length,...candidate.cases);documents.splice(0,documents.length,...candidate.documents);selectedCase='';selectedFolder='';document.querySelector('#globalSearch').value='';document.querySelector('#docSearch').value='';populateFilters();refreshReportFilters();renderAll();
}
document.querySelector('#exportBackup').onclick=async()=>{if(backupBusy)return;lockBackup(true);backupStatus('Preparazione del backup e verifica degli allegati…');try{const backup=await buildFullBackup();const url=URL.createObjectURL(new Blob([JSON.stringify(backup)],{type:'application/json'})),a=document.createElement('a');a.href=url;a.download=`PeriziaFlow_Backup_${today()}_${new Date().toTimeString().slice(0,8).replace(/:/g,'-')}.pfbackup.json`;a.click();setTimeout(()=>URL.revokeObjectURL(url),30000);backupStatus(`Backup preparato: ${backup.cases.length} pratiche, ${backup.cases.reduce((n,c)=>n+(c.deadlines||[]).length,0)} scadenze, ${backup.cases.reduce((n,c)=>n+(c.reminders||[]).length,0)} solleciti/bozze, ${backup.documents.length} documenti, ${backup.files.length} allegati caricati. Verifica il file nei download e conservalo.`);}catch(e){backupStatus('Backup non creato: '+e.message);}finally{lockBackup(false);}};
document.querySelector('#backupFile').onchange=async ev=>{if(backupBusy)return;backupCandidate=null;document.querySelector('#backupPreview').innerHTML='';const file=ev.target.files[0];if(!file){lockBackup(false);return;}lockBackup(true);backupStatus('Controllo del backup e integrità degli allegati…');
 try{if(file.size>150*1024*1024)throw Error('Limite file backup: 150 MB.');const raw=JSON.parse(await file.text());backupCandidate=await validateFullBackup(raw);const c=backupCandidate;document.querySelector('#backupPreview').innerHTML=`<div class="cards">${[['Pratiche',c.cases.length],['Note',c.cases.reduce((n,p)=>n+p.notes.length,0)],['Scadenze',c.cases.reduce((n,p)=>n+(p.deadlines||[]).length,0)],['Solleciti e bozze',c.cases.reduce((n,p)=>n+(p.reminders||[]).length,0)],['Documenti',c.documents.length],['Allegati caricati',c.files.length]].map(([k,v])=>`<div class="card"><div class="label">${k}</div><div class="value">${v}</div></div>`).join('')}</div><p>Creato il ${esc(c.createdAt)} · ${(c.bytes/1024/1024).toFixed(2)} MB di allegati.</p><p class="error">Il ripristino sostituirà ${cases.length} pratiche e ${documents.length} documenti attualmente presenti, insieme agli allegati locali. Esporta prima una copia dei dati attuali se vuoi conservarli.</p>`;backupStatus('Backup valido. Nessun dato è stato ancora modificato.');}catch(e){backupCandidate=null;backupStatus('Backup non accettato: '+e.message);}finally{lockBackup(false);}};
document.querySelector('#restoreBackup').onclick=async()=>{if(backupBusy||!backupCandidate)return;if(!confirm(`Ripristinare ${backupCandidate.cases.length} pratiche e ${backupCandidate.files.length} allegati?\n\nI dati attuali di PeriziaFlow in questo browser saranno sostituiti. Il backup deve provenire da una fonte fidata.`))return;lockBackup(true);backupStatus('Ripristino in corso…');
 try{await applyFullBackup(backupCandidate);backupCandidate=null;document.querySelector('#backupPreview').innerHTML='';document.querySelector('#backupFile').value='';backupStatus('Ripristino completato. Pratiche, note e allegati sono disponibili anche dopo la riapertura.');}catch(e){backupStatus('Ripristino non completato: '+e.message);}finally{lockBackup(false);}};
